name:                factom-did-client
version:             0.1.0.0
github:              "sigrlami/factom-did-haskell"
license:             BSD3
author:              "Sergey Bushnyak"
maintainer:          "sergey.bushnyak@sigrlami.eu"
copyright:           "2020, Sergey Bushnyak"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sigrlami/factom-did-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

# executables:
#   factom-did-haskell-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - factom-did-haskell

tests:
  factom-did-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - factom-did-client
